# coding: utf-8

"""
    notifications-api-${var.app_id}

    Notifications API  # noqa: E501

    OpenAPI spec version: 2021-10-30T06:12:55Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_sender(self):
        """Test case for delete_sender

        """
        pass

    def test_delete_sender_template(self):
        """Test case for delete_sender_template

        """
        pass

    def test_delete_template(self):
        """Test case for delete_template

        """
        pass

    def test_get_sender(self):
        """Test case for get_sender

        """
        pass

    def test_get_sender_template(self):
        """Test case for get_sender_template

        """
        pass

    def test_get_sender_templates(self):
        """Test case for get_sender_templates

        """
        pass

    def test_get_template(self):
        """Test case for get_template

        """
        pass

    def test_put_sender(self):
        """Test case for put_sender

        """
        pass

    def test_put_template(self):
        """Test case for put_template

        """
        pass

    def test_send(self):
        """Test case for send

        """
        pass


if __name__ == '__main__':
    unittest.main()
