# coding: utf-8

"""
    notifications-api-${var.app_id}

    Notifications API  # noqa: E501

    OpenAPI spec version: 2021-10-30T06:12:55Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.delete_sender_template_response import DeleteSenderTemplateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDeleteSenderTemplateResponse(unittest.TestCase):
    """DeleteSenderTemplateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteSenderTemplateResponse(self):
        """Test DeleteSenderTemplateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.delete_sender_template_response.DeleteSenderTemplateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
