# coding: utf-8

"""
    notifications-api-${var.app_id}

    Notifications API  # noqa: E501

    OpenAPI spec version: 2021-10-30T06:12:55Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="notifications-api-${var.app_id}",
    author_email="",
    url="",
    keywords=["Swagger", "notifications-api-${var.app_id}"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Notifications API  # noqa: E501
    """
)
