# coding: utf-8

# flake8: noqa
"""
    notifications-api-${var.app_id}

    Notifications API  # noqa: E501

    OpenAPI spec version: 2021-10-30T06:12:55Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.delete_sender_response import DeleteSenderResponse
from swagger_client.models.delete_sender_template_response import DeleteSenderTemplateResponse
from swagger_client.models.delete_template_response import DeleteTemplateResponse
from swagger_client.models.error import Error
from swagger_client.models.get_sender_response import GetSenderResponse
from swagger_client.models.get_sender_template_response import GetSenderTemplateResponse
from swagger_client.models.get_sender_templates_response import GetSenderTemplatesResponse
from swagger_client.models.get_template_response import GetTemplateResponse
from swagger_client.models.message import Message
from swagger_client.models.put_sender_response import PutSenderResponse
from swagger_client.models.put_template_response import PutTemplateResponse
from swagger_client.models.send_response import SendResponse
from swagger_client.models.sender import Sender
from swagger_client.models.substitution import Substitution
from swagger_client.models.template import Template
from swagger_client.models.template_substitution import TemplateSubstitution
